mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: ['chat', 'http://localhost:3000/.well-known/mercure']
                subscribe: ['*']
                
